### ISSUE TITLE
Installing conan is not working on macos

### ISSUE THREAD

**Issue by wolfee001** [turtlebrowser/get-conan#4] opened 2022-11-07 22:32 UTC
Hi,

As you can see in [this](https://github.com/wolfee001/graphi-2022-runner/actions/runs/3414601333/jobs/5682772496) pipeline, the conan is installed, but the conan --version returns an error.

It was working a couple of days ago.

Thanks,
Adam

**Comment by aniketfuryrocks** [comment] 2022-11-08 05:57
Experiencing same issue here https://github.com/mschneider/solcpp/actions/runs/3402949020/jobs/5665789983#step:3:111

**Comment by aniketfuryrocks** [comment] 2022-11-08 06:06
So, I tried to clean install this on my sisters laptop and found this
```bash
Successfully built conan patch-ng pluginbase
Installing collected packages: pluginbase, patch-ng, node-semver, bottle, urllib3, tqdm, PyYAML, python-dateutil, PyJWT, pygments, MarkupSafe, idna, fasteners, colorama, charset-normalizer, certifi, requests, Jinja2, conan
  WARNING: The script tqdm is installed in '/Users/saloniprajapati/Library/Python/3.9/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script pygmentize is installed in '/Users/saloniprajapati/Library/Python/3.9/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script normalizer is installed in '/Users/saloniprajapati/Library/Python/3.9/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The scripts conan, conan_build_info and conan_server are installed in '/Users/saloniprajapati/Library/Python/3.9/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed Jinja2-3.1.2 MarkupSafe-2.1.1 PyJWT-2.6.0 PyYAML-6.0 bottle-0.12.23 certifi-2022.9.24 charset-normalizer-2.1.1 colorama-0.4.6 conan-1.54.0 fasteners-0.18 idna-3.4 node-semver-0.6.1 patch-ng-1.17.4 pluginbase-1.0.1 pygments-2.13.0 python-dateutil-2.8.2 requests-2.28.1 tqdm-4.64.1 urllib3-1.26.12
```

**This line explains the issue**

```bash
#  WARNING: The script tqdm is installed in '/Users/saloniprajapati/Library/Python/3.9/bin' which is not on PATH.
```

The directory `~/Python/3.9/bin` is not in `$PATH`.
Adding this to `$PATH` should resolve the issue.

**works**

```bash
saloniprajapati@Salonis-MacBook-Air solcpp % ~/Library/Python/3.9/bin/conan --version
Conan version 1.54.0
```

**Comment by cqc-alec** [comment] 2022-11-08 08:23
This issue was caused by the switch to python 3.11 as the system python on the github macos VMs.
I am working around it by doing
```yml
    - name: Select Python 3.10
      # otherwise turtlebrowser/get-conan@v1.1 fails on macos-12
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
```
immediately before running this action.

**Comment by wolfee001** [comment] 2022-11-08 17:42
> This issue was caused by the switch to python 3.11 as the system python on the github macos VMs. I am working around it by doing
> 
> ```yaml
>     - name: Select Python 3.10
>       # otherwise turtlebrowser/get-conan@v1.1 fails on macos-12
>       uses: actions/setup-python@v4
>       with:
>         python-version: '3.10'
> ```
> 
> immediately before running this action.

yes, this workaround does the trick, thanks!

**Comment by patricia-gallardo** [comment] 2023-02-28 11:13
I'm closing this for now, but feel free to let me know if you need changes to the action.

**Closed as completed by patricia-gallardo** 2023-02-28 11:13 UTC
